"""Update Action model with playbook relationship

Revision ID: 083a09d44ad0
Revises: 0fe4bd50732f
Create Date: 2024-08-05 18:16:47.630582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083a09d44ad0'
down_revision = '0fe4bd50732f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playbook_action')
    op.drop_column('incident', 'playbook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('playbook', sa.VARCHAR(length=100), nullable=True))
    op.create_table('playbook_action',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('playbook_id', sa.INTEGER(), nullable=False),
    sa.Column('phase', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
