"""Initial migration

Revision ID: 8b0a3a126375
Revises: 
Create Date: 2024-08-02 19:52:12.087072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0a3a126375'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('incident_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('incident_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
