"""add playbook_id to action table

Revision ID: add_playbook_id_to_action
Revises: add_playbook_table
Create Date: 2023-08-05 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_playbook_id_to_action'
down_revision = 'add_playbook_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playbook_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_action_playbook_id', 'playbook', ['playbook_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('playbook_id')
    # ### end Alembic commands ###
